name: Greet user on issue submission

on:
  issues:
    types:
      - opened

jobs:
  greet-user:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Greet user
        uses: ./src/main.js
        id: greet_user
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
